---
- name: uninstall httpd
  hosts: all
  become_method: sudo
  become_user: root

  tasks:
  - name: disable httpd
    service:
      name: httpd
      state: stopped

  - name: delete httpd
    yum:
      name: httpd
      state: absent

  - name: delete index.html
    file:
      dest: /var/www/html/index.html
      state: absent

  - name: close 80 port
    firewalld:
      service: http
      permanent: yes
      state: disabled

  - name: close 443 port
    firewalld:
      service: https
      permanent: yes
      state: disabled

  - name: restart firewalld
    service:
      name: firewalld
      state: restarted

